### ISSUE TITLE
Clicking a link downgrades https to http

### ISSUE THREAD

**Issue by timlg07** [Java-Discord/JavaDiscordWebsite#1]
If you're on https://javadiscord.net/ and click on "Rules", you land on http://javadiscord.net/rules

The expected behavior would be the protocol staying HTTPS and IMO even upgrading HTTP to HTTPS.

The same applies to stylesheets/scripts loaded with a relative path, looks like there's something wrong with the server configuration.

**Comment by MoonTM-GIT** [comment]
Yup, should work now
